[all]
54.165.79.159 

[all:vars]
ansible_connection=ssh
ansible_user=ec2-user
ansible_sudo=true
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_user=ec2-user   
ansible_ssh_pass=Devops
                                                  
